[versions]
paper-api = "1.21.4-R0.1-SNAPSHOT"
lombok = "1.18.38"
commandapi = "10.0.1"
configlib = "4.6.1"
shadow = "8.3.6"
hikaricp = "5.0.1"
run-paper = "2.3.1"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
commandapi = { group = "dev.jorel", name = "commandapi-bukkit-core", version.ref = "commandapi" }
configlib-yaml = { group = "de.exlll", name = "configlib-yaml", version.ref = "configlib" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version.ref = "configlib" }
hikaricp = {group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp"}

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }